### ISSUE TITLE
Integration of Fingerprint reader with wonderware intouch

### ISSUE THREAD

**Issue by poonampatil55** [esmiddleton/WonderwareHistorian#1]
I want to integrate fingerprint device with wonderware Intouch SCADA. I am having fingerprint device with .net SDK file but dont know how to move further. please help

**Comment by esmiddleton** [comment]
This repo is specifically for Wonderware Historian utilities. If you have an issue with **these utitilies**, feel free to post them here. If you has issues/questions about the actually AVEVA/Wonderware software (Historian, InTouch, etc.), please direct those to AVEVA/Wonderware Technical Support or to the forums.
