### ISSUE TITLE
StateSummariesWhenNoChange.sql

### ISSUE THREAD

**Issue by raowler** [esmiddleton/WonderwareHistorian#2]
Appears to no longer work under SQL 2017 Historian 2017 U3.  Seems to only bring back first tag in list results, the rest are all 0.

has this been confirmed to work on newer versions

**Comment by esmiddleton** [comment]
There is a regression in Historian 2017 Update 3 **_SP1_** related to the INNER REMOTE JOIN clause. This did not exist in earlier releases (including Historian 2017 Update 3 without the service pack) and has been fixed for the upcoming Historian 2020 release. Would you please confirm whether your system has the service pack or not and, if it does, close the issue.

**Comment by raowler** [comment]
Yes we are Historian 2017 U3 SP1.  thnaks for the information.

**Comment by raowler** [comment]
do not suppose there is a patch to fix it?  I will talk to support

**Comment by esmiddleton** [comment]
I should have included this in my earlier message, but there is a fix available for SP1. Contact Technical Support and reference CR L00154853.

**Comment by raowler** [comment]
many thanks a lot will contact support.
